# Generated by Django 5.1.3 on 2024-11-12 09:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('user_type', models.CharField(choices=[('platform', 'Platform'), ('tenant', 'Tenant')], default='platform', max_length=50)),
                ('status', models.CharField(choices=[('deleted', 'Deleted'), ('active', 'Active'), ('inactive', 'Inactive'), ('not_verified', 'Not Verified')], default='active', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone_no', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=200)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='user',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='userApp.tenant'),
        ),
        migrations.CreateModel(
            name='UserCustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.TextField(max_length=200)),
                ('slug', models.CharField(blank=True, max_length=200)),
                ('field_type', models.CharField(choices=[('text_box', 'Text Box'), ('website_url', 'Website URL'), ('text_area', 'TextArea'), ('number', 'Number'), ('email', 'Email'), ('phone_number', 'Phone Number'), ('dropdown', 'Dropdown'), ('radio', 'Radio'), ('date', 'Date'), ('time', 'Time'), ('file', 'File Upload'), ('multiselect_checkbox', 'MultiSelect Checkbox'), ('hidden', 'Hidden'), ('heading', 'Heading'), ('paragraph', 'Paragraph')], max_length=20)),
                ('field_size', models.CharField(choices=[('col-md-12', 'Large'), ('col-md-6', 'Medium'), ('col-md-4', 'Small')], default='col-md-12', max_length=20)),
                ('placeholder', models.CharField(blank=True, max_length=200)),
                ('field_order', models.PositiveIntegerField()),
                ('custom_class_name', models.CharField(blank=True, max_length=200)),
                ('validation_rule', models.JSONField(default=dict)),
                ('is_unique', models.BooleanField(default=False)),
                ('content', models.TextField(blank=True)),
                ('content_size', models.CharField(blank=True, max_length=200)),
                ('content_alignment', models.CharField(blank=True, max_length=200)),
                ('show_on_table', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('deleted', 'Deleted'), ('active', 'Active'), ('in_active', 'InActive')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='userApp.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserCustomFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_field', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('custom_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userApp.usercustomfield')),
                ('user_submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_custom_field_values', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
