# Generated by Django 5.1.3 on 2024-11-13 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0005_group_remove_user_groups'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='group',
            new_name='groups',
        ),
    ]
