# Generated by Django 5.1.3 on 2024-11-13 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0006_rename_group_groups'),
    ]

    operations = [
        migrations.DeleteModel(
            name='groups',
        ),
    ]
