# Generated by Django 4.2.17 on 2024-12-26 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('userApp', '0012_remove_tenant_slug_tenant_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleHierarchy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_roles', to='auth.group')),
                ('parent_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_roles', to='auth.group')),
            ],
            options={
                'unique_together': {('parent_role', 'child_role')},
            },
        ),
    ]
