# Generated by Django 4.2.17 on 2024-12-27 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0013_rolehierarchy'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_forms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
